
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewerWidget(object):
    def setupUi(self, ViewerWidget):
        ViewerWidget.setObjectName("ViewerWidget")
        ViewerWidget.setEnabled(True)
        ViewerWidget.resize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ViewerWidget.sizePolicy().hasHeightForWidth())
        ViewerWidget.setSizePolicy(sizePolicy)
        ViewerWidget.setMinimumSize(QtCore.QSize(700, 500))
        ViewerWidget.setMouseTracking(True)
        self.gridLayout = QtWidgets.QGridLayout(ViewerWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_minColor = QtWidgets.QComboBox(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_minColor.sizePolicy().hasHeightForWidth())
        self.comboBox_minColor.setSizePolicy(sizePolicy)
        self.comboBox_minColor.setMinimumSize(QtCore.QSize(55, 0))
        self.comboBox_minColor.setMaximumSize(QtCore.QSize(55, 16777215))
        self.comboBox_minColor.setObjectName("comboBox_minColor")
        self.horizontalLayout.addWidget(self.comboBox_minColor)
        self.comboBox_maxColor = QtWidgets.QComboBox(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_maxColor.sizePolicy().hasHeightForWidth())
        self.comboBox_maxColor.setSizePolicy(sizePolicy)
        self.comboBox_maxColor.setMinimumSize(QtCore.QSize(55, 0))
        self.comboBox_maxColor.setMaximumSize(QtCore.QSize(55, 16777215))
        self.comboBox_maxColor.setObjectName("comboBox_maxColor")
        self.horizontalLayout.addWidget(self.comboBox_maxColor)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.Label_spectrum = QtWidgets.QLabel(ViewerWidget)
        self.Label_spectrum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_spectrum.setObjectName("Label_spectrum")
        self.gridLayout.addWidget(self.Label_spectrum, 3, 0, 1, 1)
        self.pushButton_Place = QtWidgets.QPushButton(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Place.sizePolicy().hasHeightForWidth())
        self.pushButton_Place.setSizePolicy(sizePolicy)
        self.pushButton_Place.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_Place.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_Place.setObjectName("pushButton_Place")
        self.gridLayout.addWidget(self.pushButton_Place, 2, 2, 1, 1)
        self.Label_portSelect = QtWidgets.QLabel(ViewerWidget)
        self.Label_portSelect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_portSelect.sizePolicy().hasHeightForWidth())
        self.Label_portSelect.setSizePolicy(sizePolicy)
        self.Label_portSelect.setMinimumSize(QtCore.QSize(50, 0))
        self.Label_portSelect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Label_portSelect.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_portSelect.setObjectName("Label_portSelect")
        self.gridLayout.addWidget(self.Label_portSelect, 0, 0, 1, 1)
        self.SpinBox_numberSelect = QtWidgets.QSpinBox(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_numberSelect.sizePolicy().hasHeightForWidth())
        self.SpinBox_numberSelect.setSizePolicy(sizePolicy)
        self.SpinBox_numberSelect.setMinimumSize(QtCore.QSize(120, 0))
        self.SpinBox_numberSelect.setMaximumSize(QtCore.QSize(120, 16777215))
        self.SpinBox_numberSelect.setObjectName("SpinBox_numberSelect")
        self.gridLayout.addWidget(self.SpinBox_numberSelect, 2, 1, 1, 1)
        self.Label_baudrate = QtWidgets.QLabel(ViewerWidget)
        self.Label_baudrate.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_baudrate.sizePolicy().hasHeightForWidth())
        self.Label_baudrate.setSizePolicy(sizePolicy)
        self.Label_baudrate.setMinimumSize(QtCore.QSize(50, 0))
        self.Label_baudrate.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Label_baudrate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_baudrate.setObjectName("Label_baudrate")
        self.gridLayout.addWidget(self.Label_baudrate, 1, 0, 1, 1)
        self.lineEdit_baudrate = QtWidgets.QLineEdit(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_baudrate.sizePolicy().hasHeightForWidth())
        self.lineEdit_baudrate.setSizePolicy(sizePolicy)
        self.lineEdit_baudrate.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_baudrate.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_baudrate.setObjectName("lineEdit_baudrate")
        self.gridLayout.addWidget(self.lineEdit_baudrate, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 3, 1, 1)
        self.checkBox_Terminal = QtWidgets.QCheckBox(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Terminal.sizePolicy().hasHeightForWidth())
        self.checkBox_Terminal.setSizePolicy(sizePolicy)
        self.checkBox_Terminal.setObjectName("checkBox_Terminal")
        self.gridLayout.addWidget(self.checkBox_Terminal, 1, 2, 1, 1)
        self.comboBox_port = QtWidgets.QComboBox(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_port.sizePolicy().hasHeightForWidth())
        self.comboBox_port.setSizePolicy(sizePolicy)
        self.comboBox_port.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_port.setMaximumSize(QtCore.QSize(120, 16777215))
        self.comboBox_port.setObjectName("comboBox_port")
        self.gridLayout.addWidget(self.comboBox_port, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_minColor = QtWidgets.QLineEdit(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_minColor.sizePolicy().hasHeightForWidth())
        self.lineEdit_minColor.setSizePolicy(sizePolicy)
        self.lineEdit_minColor.setMinimumSize(QtCore.QSize(55, 0))
        self.lineEdit_minColor.setMaximumSize(QtCore.QSize(55, 16777215))
        self.lineEdit_minColor.setObjectName("lineEdit_minColor")
        self.horizontalLayout_2.addWidget(self.lineEdit_minColor)
        self.lineEdit_maxColor = QtWidgets.QLineEdit(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_maxColor.sizePolicy().hasHeightForWidth())
        self.lineEdit_maxColor.setSizePolicy(sizePolicy)
        self.lineEdit_maxColor.setMinimumSize(QtCore.QSize(55, 0))
        self.lineEdit_maxColor.setMaximumSize(QtCore.QSize(55, 16777215))
        self.lineEdit_maxColor.setObjectName("lineEdit_maxColor")
        self.horizontalLayout_2.addWidget(self.lineEdit_maxColor)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.pushButton_Connect = QtWidgets.QPushButton(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Connect.sizePolicy().hasHeightForWidth())
        self.pushButton_Connect.setSizePolicy(sizePolicy)
        self.pushButton_Connect.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_Connect.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.gridLayout.addWidget(self.pushButton_Connect, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        self.Label_sensorNumber = QtWidgets.QLabel(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_sensorNumber.sizePolicy().hasHeightForWidth())
        self.Label_sensorNumber.setSizePolicy(sizePolicy)
        self.Label_sensorNumber.setMinimumSize(QtCore.QSize(100, 0))
        self.Label_sensorNumber.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Label_sensorNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_sensorNumber.setObjectName("Label_sensorNumber")
        self.gridLayout.addWidget(self.Label_sensorNumber, 2, 0, 1, 1)
        self.widget_Mpl = MplWidget(ViewerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Mpl.sizePolicy().hasHeightForWidth())
        self.widget_Mpl.setSizePolicy(sizePolicy)
        self.widget_Mpl.setAutoFillBackground(False)
        self.widget_Mpl.setStyleSheet("background-color: rgb(57, 57, 57);")
        self.widget_Mpl.setObjectName("widget_Mpl")
        self.gridLayout.addWidget(self.widget_Mpl, 6, 0, 1, 5)
        self.Layout_terminal = QtWidgets.QGridLayout()
        self.Layout_terminal.setObjectName("Layout_terminal")
        self.terminal = QtWidgets.QTextEdit(ViewerWidget)
        self.terminal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal.sizePolicy().hasHeightForWidth())
        self.terminal.setSizePolicy(sizePolicy)
        self.terminal.setMinimumSize(QtCore.QSize(250, 100))
        self.terminal.setMaximumSize(QtCore.QSize(16777215, 100))
        self.terminal.setMouseTracking(True)
        self.terminal.setStyleSheet("background-color: rgb(53, 53, 53);\n"
"color: rgb(226, 226, 226);\n"
"disabled {background-color: rgb(0, 0, 0); }\n"
"")
        self.terminal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.terminal.setFrameShadow(QtWidgets.QFrame.Plain)
        self.terminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.terminal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.terminal.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.terminal.setReadOnly(True)
        self.terminal.setAcceptRichText(False)
        self.terminal.setObjectName("terminal")
        self.Layout_terminal.addWidget(self.terminal, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_terminal.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.Layout_terminal, 0, 4, 4, 1)

        self.retranslateUi(ViewerWidget)
        QtCore.QMetaObject.connectSlotsByName(ViewerWidget)

    def retranslateUi(self, ViewerWidget):
        _translate = QtCore.QCoreApplication.translate
        ViewerWidget.setWindowTitle(_translate("ViewerWidget", "Form"))
        self.Label_spectrum.setText(_translate("ViewerWidget", "Color spectrum:"))
        self.pushButton_Place.setText(_translate("ViewerWidget", "Place Sensors"))
        self.Label_portSelect.setText(_translate("ViewerWidget", "Data Port:"))
        self.Label_baudrate.setText(_translate("ViewerWidget", "Baudrate:"))
        self.checkBox_Terminal.setText(_translate("ViewerWidget", "Show Terminal"))
        self.pushButton_Connect.setText(_translate("ViewerWidget", "Connect"))
        self.Label_sensorNumber.setText(_translate("ViewerWidget", "Number of sensors:"))

from mplWidget import MplWidget
