
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(307, 147)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_showName = QtWidgets.QCheckBox(Dialog)
        self.checkBox_showName.setObjectName("checkBox_showName")
        self.gridLayout_2.addWidget(self.checkBox_showName, 0, 2, 1, 1)
        self.lineEdit_Name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.gridLayout_2.addWidget(self.lineEdit_Name, 0, 1, 1, 1)
        self.lineEdit_re = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_re.setObjectName("lineEdit_re")
        self.gridLayout_2.addWidget(self.lineEdit_re, 1, 1, 1, 1)
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.gridLayout_2.addWidget(self.label_name, 0, 0, 1, 1)
        self.label_re = QtWidgets.QLabel(Dialog)
        self.label_re.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_re.setObjectName("label_re")
        self.gridLayout_2.addWidget(self.label_re, 1, 0, 1, 1)
        self.label_colorMap = QtWidgets.QLabel(Dialog)
        self.label_colorMap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_colorMap.setObjectName("label_colorMap")
        self.gridLayout_2.addWidget(self.label_colorMap, 2, 0, 1, 1)
        self.lineEdit_min = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_min.setObjectName("lineEdit_min")
        self.gridLayout_2.addWidget(self.lineEdit_min, 3, 1, 1, 1)
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout_2.addWidget(self.pushButton_ok, 4, 2, 1, 1)
        self.checkBox_showEquation = QtWidgets.QCheckBox(Dialog)
        self.checkBox_showEquation.setObjectName("checkBox_showEquation")
        self.gridLayout_2.addWidget(self.checkBox_showEquation, 1, 2, 1, 1)
        self.comboBox_colorMap = QtWidgets.QComboBox(Dialog)
        self.comboBox_colorMap.setObjectName("comboBox_colorMap")
        self.gridLayout_2.addWidget(self.comboBox_colorMap, 2, 1, 1, 1)
        self.label_minValue = QtWidgets.QLabel(Dialog)
        self.label_minValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_minValue.setObjectName("label_minValue")
        self.gridLayout_2.addWidget(self.label_minValue, 3, 0, 1, 1)
        self.label_maxValue = QtWidgets.QLabel(Dialog)
        self.label_maxValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_maxValue.setObjectName("label_maxValue")
        self.gridLayout_2.addWidget(self.label_maxValue, 4, 0, 1, 1)
        self.lineEdit_max = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_max.setObjectName("lineEdit_max")
        self.gridLayout_2.addWidget(self.lineEdit_max, 4, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox_showName.setText(_translate("Dialog", "Show Name"))
        self.label_name.setText(_translate("Dialog", "Name:"))
        self.label_re.setText(_translate("Dialog", "re:"))
        self.label_colorMap.setText(_translate("Dialog", "Color Map:"))
        self.pushButton_ok.setText(_translate("Dialog", "Ok"))
        self.checkBox_showEquation.setText(_translate("Dialog", "Show Equation"))
        self.label_minValue.setText(_translate("Dialog", "Min Value:"))
        self.label_maxValue.setText(_translate("Dialog", "Max Value:"))

